import { useEffect, useState } from "react";
import { createRoot } from "react-dom/client";
import "./styles.css";
import "./charts.css";
import "./auth.css";

const API = import.meta.env.VITE_FORESTWATCH_API || "http://127.0.0.1:8000";
const pct = (value) => `${Number(value || 0).toFixed(2)}%`;

function Dashboard({account, onLogout}) {
  const [section, setSection] = useState("Dashboard");
  const [alerts, setAlerts] = useState([]);
  const [dates, setDates] = useState([]);
  const [series, setSeries] = useState([]);
  const [timelineInterval, setTimelineInterval] = useState("yearly");
  const [earlier, setEarlier] = useState("");
  const [later, setLater] = useState("");
  const [summary, setSummary] = useState(null);
  const [error, setError] = useState("");
  const [loading, setLoading] = useState(false);

  useEffect(() => {
    fetch(`${API}/api/ndvi/dates`).then((r) => r.json()).then((payload) => {
      const unique = payload.dates || [];
      setDates(unique); setEarlier(unique[0] || ""); setLater(unique.at(-1) || "");
    }).catch(() => setError("Start the FastAPI service on port 8000 to load GIS dates."));
  }, []);
  useEffect(() => {
    fetch(`${API}/api/ndvi/timeline?interval=${timelineInterval}`).then((r) => r.ok ? r.json() : []).then((rows) => setSeries(rows.filter((row) => Number.isFinite(row.ndvi_mean)))).catch(() => {});
  }, [timelineInterval]);
  useEffect(() => {
    fetch(`${API}/api/alerts/check`, {method:"POST", headers:{Authorization:`Bearer ${account.token}`}})
      .then((r) => r.json()).then((result) => { if (result.email_delivery?.message) setError(result.email_delivery.message); })
      .catch(() => {});
  }, [account.token]);
  useEffect(() => { fetch(`${API}/api/alerts`).then(r=>r.ok?r.json():[]).then(setAlerts).catch(()=>{}); }, []);

  const load = async () => {
    if (!earlier || !later || earlier === later) return setError("Choose two different observation dates.");
    setLoading(true); setError("");
    try {
      const response = await fetch(`${API}/api/gis/dashboard?earlier_date=${earlier}&later_date=${later}`);
      const payload = await response.json();
      if (!response.ok) throw new Error(payload.detail || "Unable to calculate the selected period.");
      setSummary(payload);
    } catch (e) { setError(e.message); } finally { setLoading(false); }
  };
  const refreshDashboard = async () => {
    setLoading(true); setError("");
    try {
      const [dateResponse, seriesResponse] = await Promise.all([
        fetch(`${API}/api/ndvi/dates`),
        fetch(`${API}/api/ndvi/timeline?interval=${timelineInterval}`),
      ]);
      const datePayload = await dateResponse.json();
      const refreshedDates = datePayload.dates || [];
      setDates(refreshedDates);
      setEarlier((current) => refreshedDates.includes(current) ? current : (refreshedDates[0] || ""));
      setLater((current) => refreshedDates.includes(current) ? current : (refreshedDates.at(-1) || ""));
      if (seriesResponse.ok) {
        const rows = await seriesResponse.json();
        setSeries(rows.filter((row) => Number.isFinite(row.ndvi_mean)));
      }
    } catch { setError("Unable to refresh the satellite dataset. Check that the API is running."); }
    finally { setLoading(false); }
  };

  const navItems=["Dashboard","Change map","Upload images","Predictions","Model comparison","Alerts","Reports"];
  const showDashboard=section==="Dashboard";
  return <main className="vision-shell">
    <aside className="vision-sidebar"><div className="brand"><span>❧</span><b>Forest<span>Watch</span></b></div><nav>{navItems.map(item=><button key={item} className={section===item?"selected":""} onClick={()=>setSection(item)}>{navIcon(item)}<span>{item}</span></button>)}</nav><div className="sidebar-footer">❧<small>Monitor<br/>Conserve<br/>Sustain</small></div></aside>
    <section className="vision-main"><header className="vision-header"><div><h1>Forest Monitoring</h1><p>{settingsText(summary?.period || `${earlier || "—"} to ${later || "—"}`)}</p></div><div className="header-actions"><span className="user-dot">●</span><span className="account-email">{account.email}</span><button className="secondary" onClick={refreshDashboard} disabled={loading}>↻ Refresh</button><button className="secondary" onClick={onLogout}>Sign out</button></div></header>
    {showDashboard && <><section className="period-controls"><label>Earlier observation<select value={earlier} onChange={(e) => setEarlier(e.target.value)}>{dates.map((d) => <option key={d}>{d}</option>)}</select></label><span>→</span><label>Later observation<select value={later} onChange={(e) => setLater(e.target.value)}>{dates.map((d) => <option key={d}>{d}</option>)}</select></label><button onClick={load} disabled={loading}>{loading ? "Updating…" : "Update view"}</button></section>{error && <div className="notice">{error}</div>}
    <section className="vision-metrics"><VisionMetric icon="●" title="Stable area" value={pct(summary?.stable_pixel_percentage)} detail="selected boundary area" tone="yellow"/><VisionMetric icon="↓" title="Vegetation decrease" value={pct(summary?.decrease_pixel_percentage)} detail="selected boundary area" tone="red"/><VisionMetric icon="↑" title="Vegetation increase" value={pct(summary?.increase_pixel_percentage)} detail="selected boundary area" tone="green"/><VisionMetric icon="⌖" title="Active alerts" value={String(alerts.filter(a=>a.status!=="RESOLVED"&&a.status!=="CLOSED").length)} detail="health-score alerts" tone="blue"/></section>
    <section className="vision-grid"><article className="vision-panel map-card"><div className="vision-panel-head"><h2>◈ Forest change imagery</h2><span>True colour · selected dates</span></div><div className="vision-scenes"><figure><img src={earlier?`${API}/api/gis/true-colour/${earlier}`:""} alt={`Earlier forest scene ${earlier}`}/><figcaption>Earlier · {earlier||"—"}</figcaption></figure><figure><img src={later?`${API}/api/gis/true-colour/${later}`:""} alt={`Later forest scene ${later}`}/><figcaption>Later · {later||"—"}</figcaption></figure></div></article><article className="vision-panel distribution-panel"><div className="vision-panel-head"><div><small>CHANGE BREAKDOWN</small><h2>Selected-period distribution</h2></div></div><ChangePie summary={summary}/><ComparisonInsight summary={summary} earlier={earlier} later={later}/></article><article className="vision-panel timeline-panel"><div className="vision-panel-head"><h2>▥ Change timeline</h2><label className="timeline-select">Timeline<select value={timelineInterval} onChange={e=>setTimelineInterval(e.target.value)}><option value="yearly">Yearly</option><option value="monthly">Monthly</option></select></label></div><TrendChart values={series} interval={timelineInterval}/></article><article className="vision-panel alert-card"><div className="vision-panel-head"><h2>♟ Recent alerts</h2><button onClick={()=>setSection("Alerts")}>View all →</button></div><RecentAlerts rows={alerts}/></article></section></>}
    {section === "Upload images" && <UploadSection />}
    {section === "Predictions" && <PredictionSection />}
    {section === "Change map" && <ChangeMapSection dates={dates} earlier={earlier} later={later} setEarlier={setEarlier} setLater={setLater} onUpdate={load} loading={loading} summary={summary}/>} 
    {section === "Model comparison" && <ModelComparisonSection />}
    {section === "Alerts" && <AlertsSection token={account.token} />}
    {section === "Reports" && <ReportsSection />}
    </section></main>;
}
function App() {
  const [account, setAccount] = useState(() => { try { return JSON.parse(localStorage.getItem("forestwatch-user")); } catch { return null; } });
  return account ? <Dashboard account={account} onLogout={() => { localStorage.removeItem("forestwatch-user"); setAccount(null); }} /> : <Login onLogin={setAccount}/>;
}
function Login({onLogin}) {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [isRegister, setRegister] = useState(false); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const submit = async (event) => { event.preventDefault(); setBusy(true); setMessage(""); try { const r=await fetch(`${API}/api/auth/${isRegister ? "register" : "login"}`, {method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({email,password})}); const p=await r.json(); if(!r.ok) throw new Error(p.detail || "Unable to sign in."); localStorage.setItem("forestwatch-user",JSON.stringify(p)); onLogin(p); } catch(e) { setMessage(e.message); } finally { setBusy(false); } };
  return <main className="login-page"><form className="login-card" onSubmit={submit}><span className="eyebrow">FORESTWATCH</span><h1>Forest Monitoring</h1><p>Sign in to access the GIS dashboard and receive health alerts at this email address.</p><label>Email address<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required /></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} minLength="8" required /></label>{message && <div className="notice">{message}</div>}<button type="submit">{busy ? "Please wait…" : isRegister ? "Create account" : "Sign in"}</button><button className="link-button" type="button" onClick={()=>setRegister(!isRegister)}>{isRegister ? "Already have an account? Sign in" : "New user? Create an account"}</button></form></main>;
}
function Metric({ title, value, tone, detail }) { return <article className={`metric ${tone}`}><span>{title}</span><strong>{value}</strong><small>{detail}</small></article>; }
function settingsText(period){return `Satellite monitoring · ${period}`}
function navIcon(item){return ({"Dashboard":"⌂","Change map":"◈","Forest change":"♜","Analytics":"▥","Reports":"▤","Alerts":"♟","Upload images":"⇧","Predictions":"⌁","Model comparison":"⚖"})[item]||"•"}
function VisionMetric({icon,title,value,detail,tone}){return <article className={`vision-metric ${tone}`}><span className="vision-icon">{icon}</span><div><small>{title}</small><strong>{value}</strong><em>{detail}</em></div></article>}
function ChangePie({summary}){const decrease=Number(summary?.decrease_pixel_percentage||0),stable=Number(summary?.stable_pixel_percentage||0),increase=Number(summary?.increase_pixel_percentage||0),total=decrease+stable+increase;const d=total?decrease/total*100:0,s=total?stable/total*100:0,i=total?increase/total*100:0,style={background:`conic-gradient(#ef5e68 0 ${d}%,#f4cc42 ${d}% ${d+s}%,#40e08a ${d+s}% 100%)`};return <div className="change-pie-wrap"><div className="change-pie" style={style}><span>{total?"100%":"—"}<small>boundary</small></span></div><div className="change-pie-key"><span><i className="pie-decrease"/>Decrease <b>{pct(decrease)}</b></span><span><i className="pie-stable"/>Stable <b>{pct(stable)}</b></span><span><i className="pie-increase"/>Increase <b>{pct(increase)}</b></span></div></div>}
function ComparisonInsight({summary,earlier,later}){const decrease=Number(summary?.decrease_pixel_percentage||0),increase=Number(summary?.increase_pixel_percentage||0);const direction=decrease>increase?"Vegetation decrease is the dominant detected change.":increase>decrease?"Vegetation increase is the dominant detected change.":"No dominant vegetation change is detected.";return <section className="comparison-insight"><span>SELECTED COMPARISON</span><strong>{earlier||"—"} → {later||"—"}</strong><p>{direction}</p><div><small>Change threshold</small><b>0.15 NDVI index</b></div><p className="insight-note">{summary?.interpretation||"Select two dates and update the dashboard to calculate the comparison."}</p></section>}
function RecentAlerts({rows}){const active=rows.filter(row=>row.status!=="RESOLVED"&&row.status!=="CLOSED").slice(0,4);if(!active.length)return <p className="empty-alerts">No active vegetation health alerts.</p>;return <div className="recent-alerts">{active.map(row=><div key={row.alert_id}><b>{row.severity==="CRITICAL"?"▲":"!"}</b><span><strong>{row.severity==="CRITICAL"?"Possible vegetation decline":"Vegetation health alert"}</strong><small>{row.reason}</small></span><time>{row.date}</time></div>)}</div>}
function Bar({ label, value, color }) { const safe = Number(value || 0); return <div className="bar-row"><span>{label}</span><div className="track"><i style={{width: `${Math.min(100, safe)}%`, background: color}} /></div><b>{pct(safe)}</b></div>; }
function TrendChart({values,interval="yearly"}) { if (!values.length) return <p className="caption">{interval[0].toUpperCase()+interval.slice(1)} NDVI observations will appear here.</p>; const ys=values.map(v=>v.ndvi_mean), lo=Math.min(...ys), hi=Math.max(...ys), pad=Math.max(.03,(hi-lo)*.12); const y=v=>145-((v-(lo-pad))/((hi+pad)-(lo-pad)||1))*120; const x=i=>40+i*(540/Math.max(1,values.length-1)); const points=values.map((v,i)=>`${x(i)},${y(v.ndvi_mean)}`).join(" "); const labelIndexes=interval==="monthly"?[0,Math.floor((values.length-1)/3),Math.floor(2*(values.length-1)/3),values.length-1]:values.map((_,i)=>i); return <svg className="trend-chart" viewBox="0 0 620 190" role="img" aria-label={`${interval} NDVI index trend`}><line x1="40" y1="15" x2="40" y2="145"/><line x1="40" y1="145" x2="590" y2="145"/><polyline points={points}/>{values.map((v,i)=><circle key={v.date} cx={x(i)} cy={y(v.ndvi_mean)} r="3"><title>{`${v.date}: ${(v.ndvi_mean*100).toFixed(2)}%`}</title></circle>)}{labelIndexes.map(i=><text key={values[i].date} x={x(i)} y="171" textAnchor="middle">{values[i].date}</text>)}<text x="4" y="20">{hi.toFixed(2)}</text><text x="4" y="148">{lo.toFixed(2)}</text></svg>; }
function Donut({summary}) { const d=Number(summary?.decrease_pixel_percentage||0), s=Number(summary?.stable_pixel_percentage||0), i=Number(summary?.increase_pixel_percentage||0); const style={background:`conic-gradient(#ef5e68 0 ${d}%, #6c8cff ${d}% ${d+s}%, #40c98a ${d+s}% 100%)`}; return <div className="donut-wrap"><div className="donut" style={style}><div>{(d+s+i).toFixed(0)}%<small>boundary</small></div></div><div className="donut-key"><span>■ Decrease {pct(d)}</span><span>■ Stable {pct(s)}</span><span>■ Increase {pct(i)}</span></div></div>; }
function UploadSection(){const [files,setFiles]=useState(null),[type,setType]=useState("Sentinel-2 NDVI"),[date,setDate]=useState(""),[message,setMessage]=useState("");const submit=async e=>{e.preventDefault();if(!files?.length)return setMessage("Choose one or more image files.");const body=new FormData();[...files].forEach(f=>body.append("files",f));body.append("image_type",type);body.append("acquisition_date",date);const r=await fetch(`${API}/api/uploads`,{method:"POST",body});const p=await r.json();setMessage(r.ok?`Added ${p.added} image(s) dated ${p.date}.`:p.detail)};return <section className="feature-panel"><h2>Satellite image upload</h2><p>Upload dated Sentinel imagery into the local ForestWatch dataset.</p><form onSubmit={submit}><label>Images<input type="file" multiple accept="image/*,.tif,.tiff,.jp2" onChange={e=>setFiles(e.target.files)}/></label><label>Image type<select value={type} onChange={e=>setType(e.target.value)}>{["Sentinel-1 VV","Sentinel-1 VH","Sentinel-2 NDVI","Sentinel-2 True Color"].map(x=><option key={x}>{x}</option>)}</select></label><label>Acquisition date<input type="date" required value={date} onChange={e=>setDate(e.target.value)}/></label><button>Add images to dataset</button></form><p className="caption">{message}</p></section>}
function PredictionSection(){const [months,setMonths]=useState(6),[rows,setRows]=useState([]),[message,setMessage]=useState("");const run=async()=>{setMessage("Training local forecast model…");const r=await fetch(`${API}/api/predictions/forecast?horizon=${months}`);const p=await r.json();if(!r.ok)return setMessage(p.detail);setRows(p);setMessage(`Generated ${p.length} future prediction(s).`)};return <section className="feature-panel"><h2>Future NDVI prediction</h2><p>The backend trains a local Random Forest from historical observations before forecasting.</p><label>Months to predict<input type="number" min="1" max="24" value={months} onChange={e=>setMonths(e.target.value)}/></label><button onClick={run}>Generate future prediction</button><p className="caption">{message}</p><PredictionChart rows={rows}/><SimpleTable rows={rows} columns={["forecast_date","predicted_ndvi_percent"]}/></section>}
function ModelComparisonSection(){const [epochs,setEpochs]=useState(5),[results,setResults]=useState([]),[message,setMessage]=useState(""),[busy,setBusy]=useState(false);const run=async()=>{setBusy(true);setMessage("Preparing labelled tiles and training CNN and YOLO… this may take several minutes on CPU.");try{const r=await fetch(`${API}/api/models/cnn-yolo-compare?epochs=${encodeURIComponent(epochs)}`,{method:"POST"});const p=await r.json();if(!r.ok)throw new Error(p.detail||"Model comparison could not complete.");setResults(p.results||[]);setMessage(String(p.note||"Comparison complete.").replace(/^###\s*/,""))}catch(e){setMessage(e.message)}finally{setBusy(false)}};return <section className="feature-panel model-comparison"><h2>CNN vs YOLO change-detection comparison</h2><p>Compare a compact CNN tile classifier with YOLOv8n object detection on the labelled 2024–2025 Gorewada change dataset.</p><div className="model-controls"><label>Training epochs<input type="number" min="1" step="1" value={epochs} onChange={e=>setEpochs(e.target.value)}/><small>Start with 5 epochs; enter a higher value when a longer training run is needed.</small></label><button onClick={run} disabled={busy}>{busy?"Running comparison…":"Run CNN vs YOLO comparison"}</button></div><p className="caption">{message}</p>{results.length>0&&<><ModelMetricChart rows={results}/><ModelResults rows={results}/></>}</section>}
function ModelMetricChart({rows}){const metrics=["precision","recall","f1","mAP50"],labels={precision:"Precision",recall:"Recall",f1:"F1 score",mAP50:"mAP 50"},cnn=rows.find(row=>row.model?.includes("CNN"))||{},yolo=rows.find(row=>row.model?.includes("YOLO"))||{};return <figure className="model-chart"><figcaption><strong>CNN vs YOLO metrics</strong><span>Held-out change detection (%)</span></figcaption><div className="metric-chart-key"><span><i className="cnn-key"/>CNN</span><span><i className="yolo-key"/>YOLOv8n</span></div>{metrics.map(metric=><div className="model-bar" key={metric}><label>{labels[metric]}</label><div><i className="cnn-bar" style={{width:`${Math.max(0,Math.min(100,Number(cnn[metric]||0)*100))}%`}}/><i className="yolo-bar" style={{width:`${Math.max(0,Math.min(100,Number(yolo[metric]||0)*100))}%`}}/></div><b>{(Number(cnn[metric]||0)*100).toFixed(1)}% / {(Number(yolo[metric]||0)*100).toFixed(1)}%</b></div>)}</figure>}
function ChangeMapSection({dates,earlier,later,setEarlier,setLater,onUpdate,loading,summary}){const [mapError,setMapError]=useState("");const update=async()=>{setMapError("");if(!earlier||!later||earlier===later)return setMapError("Choose two different observation dates.");await onUpdate()};const url=earlier&&later?`${API}/api/gis/change-overlay/${earlier}/${later}?v=${encodeURIComponent(`${earlier}-${later}`)}`:"";return <section className="feature-panel change-map-panel"><h2>Forest change map</h2><p>View vegetation decrease, increase, and stable areas over the real later true-colour satellite scene.</p><div className="change-map-controls"><label>Earlier date<select value={earlier} onChange={e=>setEarlier(e.target.value)}>{dates.map(date=><option key={date}>{date}</option>)}</select></label><label>Later date<select value={later} onChange={e=>setLater(e.target.value)}>{dates.map(date=><option key={date}>{date}</option>)}</select></label><button onClick={update} disabled={loading}>{loading?"Building map…":"Show change map"}</button></div>{mapError&&<div className="notice">{mapError}</div>}{summary&&<div className="map-summary"><span>Decrease {pct(summary.decrease_pixel_percentage)}</span><span>Stable {pct(summary.stable_pixel_percentage)}</span><span>Increase {pct(summary.increase_pixel_percentage)}</span></div>}<div className="change-map-wrap">{url&&<img src={url} alt={`Forest vegetation change map from ${earlier} to ${later}`}/>}<div className="change-map-legend"><span><i className="loss"/>Decrease</span><span><i className="stable-key"/>Stable</span><span><i className="gain"/>Increase</span></div></div><p className="caption">Red marks detected decrease, green marks increase, and transparent yellow marks stable area. The imagery remains the actual later satellite scene.</p></section>}
function ModelResults({rows}){const metrics=["accuracy","precision","recall","f1","mAP50","mAP50_95"];return <div className="model-result-grid">{rows.map(row=><article key={row.model}><h3>{row.model}</h3><p>{row.evaluation||row.status||"Evaluation status unavailable"}</p><dl>{metrics.filter(metric=>typeof row[metric]==="number").map(metric=><div key={metric}><dt>{metric.replace("mAP","mAP ").replaceAll("_"," ")}</dt><dd>{(row[metric]*100).toFixed(2)}%</dd></div>)}</dl>{typeof row.training_change_tiles==="number"&&<div className="model-samples">Changed training tiles: <b>{row.training_change_tiles}</b> · Held-out change tiles: <b>{row.test_change_tiles}</b>{typeof row.positive_tile_augmentations==="number"&&<> · Positive augmentations: <b>{row.positive_tile_augmentations}</b></>}</div>}{row.detail&&<small>{row.detail}</small>}</article>)}</div>}
function PredictionChart({rows}){const points=rows.map(row=>({date:String(row.forecast_date||""),value:Number(row.predicted_ndvi_percent)})).filter(row=>Number.isFinite(row.value));if(!points.length)return <div className="prediction-empty">Generate a forecast to view its NDVI trend.</div>;const values=points.map(point=>point.value),low=Math.max(0,Math.floor(Math.min(...values)-5)),high=Math.min(100,Math.ceil(Math.max(...values)+5)),range=Math.max(1,high-low),x=index=>68+index*(690/Math.max(1,points.length-1)),y=value=>242-((value-low)/range)*184,polyline=points.map((point,index)=>`${x(index)},${y(point.value)}`).join(" ");const labels=[0,Math.floor((points.length-1)/2),points.length-1].filter((value,index,array)=>array.indexOf(value)===index);return <figure className="prediction-figure"><figcaption><strong>Predicted vegetation trend</strong><span>NDVI (%)</span></figcaption><svg className="prediction-chart" viewBox="0 0 800 300" role="img" aria-label="Line chart of future predicted NDVI percentage"><title>Future predicted NDVI</title><line className="prediction-grid" x1="68" y1="58" x2="758" y2="58"/><line className="prediction-grid" x1="68" y1="150" x2="758" y2="150"/><line className="prediction-grid" x1="68" y1="242" x2="758" y2="242"/><line className="prediction-axis" x1="68" y1="42" x2="68" y2="242"/><line className="prediction-axis" x1="68" y1="242" x2="758" y2="242"/><text x="12" y="62">{high.toFixed(0)}%</text><text x="12" y="154">{((low+high)/2).toFixed(0)}%</text><text x="12" y="246">{low.toFixed(0)}%</text><polyline className="prediction-line" points={polyline}/>{points.map((point,index)=><g key={`${point.date}-${index}`}><circle className="prediction-point" cx={x(index)} cy={y(point.value)} r="5"/><title>{`${point.date}: ${point.value.toFixed(2)}%`}</title></g>)}{labels.map(index=><text className="prediction-date" key={index} x={x(index)} y="278" textAnchor={index===0?"start":index===points.length-1?"end":"middle"}>{points[index].date}</text>)}</svg><div className="prediction-summary"><span>Lowest: <b>{Math.min(...values).toFixed(2)}%</b></span><span>Highest: <b>{Math.max(...values).toFixed(2)}%</b></span></div></figure>}
function AlertsSection({token}){const [rows,setRows]=useState([]),[message,setMessage]=useState("");const load=async()=>{try{const check=await fetch(`${API}/api/alerts/check`,{method:"POST",headers:{Authorization:`Bearer ${token}`}});const checkData=await check.json();const r=await fetch(`${API}/api/alerts`);setRows(await r.json());setMessage(checkData.email_delivery?.message||checkData.message||checkData.detail||"Unable to check email delivery.")}catch{setMessage("Unable to contact the alerts service.")}};useEffect(()=>{load()},[]);return <section className="feature-panel"><h2>Vegetation health alerts</h2><p>Alert threshold: health score below 35. Alerts are sent to the signed-in email when SMTP is configured.</p><button onClick={load}>Refresh alerts</button><p className="caption">{message}</p><SimpleTable rows={rows} columns={["date","severity","reason","status","recommended_action"]}/></section>}
function ReportsSection(){const [period,setPeriod]=useState("monthly"),[available,setAvailable]=useState({months:[],years:[]}),[selected,setSelected]=useState(""),[message,setMessage]=useState("");const loadPeriods=async()=>{try{setMessage("Loading available report dates…");const r=await fetch(`${API}/api/reports/available-periods`);const p=await r.json();if(!r.ok)throw new Error(p.detail||"Unable to load report dates.");const months=p.months||[],years=p.years||[];setAvailable({months,years});const choices=period==="monthly"?months:years;setSelected(choices.at(-1)||"");setMessage(choices.length?"":"No NDVI observations are available for this report type.")}catch(e){setMessage(e.message||"Start the backend to load available report dates.")}};useEffect(()=>{loadPeriods()},[]);const choices=period==="monthly"?available.months:available.years;const changePeriod=value=>{setPeriod(value);const next=value==="monthly"?available.months:available.years;setSelected(next.at(-1)||"")};const download=format=>{if(!selected)return setMessage("Choose a report date first.");window.open(`${API}/api/reports/${period}/download?format=${format}&report_date=${encodeURIComponent(selected)}`,format==="html"?"_blank":"_self")};return <section className="feature-panel"><h2>Monitoring reports</h2><p>Choose the month or year before downloading a report. Only periods that contain NDVI observations are shown.</p><div className="report-picker"><label>Report type<select value={period} onChange={e=>changePeriod(e.target.value)}><option value="monthly">Monthly</option><option value="yearly">Yearly</option></select></label><label>{period==="monthly"?"Month":"Year"}<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Choose {period==="monthly"?"month":"year"}</option>{choices.map(value=><option key={value} value={value}>{value}</option>)}</select></label><button className="secondary" onClick={loadPeriods}>↻ Load dates</button></div><div className="report-grid"><article><h3>{period==="monthly"?"Monthly":"Yearly"} report: {selected||"—"}</h3><button onClick={()=>download("html")}>Download HTML report</button><button className="secondary" onClick={()=>download("csv")}>Download CSV metrics</button></article></div><p className="caption">{message}</p></section>}
function SimpleTable({rows,columns}){if(!rows?.length)return null;return <div className="table-wrap"><table><thead><tr>{columns.map(c=><th key={c}>{c.replaceAll("_"," ")}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{columns.map(c=><td key={c}>{row[c] ?? "—"}</td>)}</tr>)}</tbody></table></div>}
createRoot(document.getElementById("root")).render(<App />);
